baseurl      = "https://sumb0dy.com"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

PygmentsCodeFences = true
PygmentsStyle = "monokai"



[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Ighor Tavares"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Hack Things | Learn Stuff | Have Fun"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  enableThemeToggle = true

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/%E2%8C%A8%EF%B8%8Fighor-tavares-101b75b7/"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/sum_b0dy"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Welcome To My 172.0.0.1"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoMark  = ">"
      logoText = "$ cd /home/ighor/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [menu]
    [[menu.main]]
        identifier = "blog"
        name       = "Blog"
        url        = "/posts"
    [[menu.main]]
        identifier = "about"
        name       = "About"
        url        = "about/"
    [[menu.main]]
        identifier = "projects"
        name       = "Projects"
        url        = "project/"
